tool_surface:
  # One of: masters | domains | hybrid
  mode: domains

  # If set to true/false, overrides all wrapper exposure env flags
  enable_wrappers: false

  # Per-domain toggles (used when mode is domains or hybrid)
  domains:
    envelope: true
    internal_loads: true
    hvac: true
    outputs: true

